name: AareEdgeDemo

options:
  bundleIdPrefix: com.aare.edge
  deploymentTarget:
    iOS: 16.0

packages:
  AareEdgeSDK:
    path: ../AareEdgeSDK

targets:
  AareEdgeDemo:
    type: application
    platform: iOS
    sources:
      - path: AareEdgeDemo
        type: group
      - path: vocab.txt
        type: file
        buildPhase: resources
      - path: hipaa_phi_detector.mlpackage
    dependencies:
      - package: AareEdgeSDK
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aare.edge.AareEdgeDemo
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
